---
services:
  flask-app:
    image: foi-fe:latest
    container_name: foi-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9003:80'
    networks:
      - foi_network_fe

networks:
  foi_network_fe:
    name: foi_network_fe
